# Generated by Django 5.0.6 on 2024-05-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="img")),
                ("description", models.TextField(max_length=2555)),
                ("popularity", models.IntegerField(default=5)),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Length in centimeters",
                        max_digits=2,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=0, help_text="Width in centimeters", max_digits=2
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
