# Generated by Django 5.0.6 on 2024-05-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
