# Generated by Django 5.0.6 on 2024-06-19 10:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_item_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
