# Generated by Django 5.0.6 on 2024-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0007_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="img"),
        ),
    ]
