# Generated by Django 5.0.6 on 2024-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0012_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
    ]
