version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - liveartcorner-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5555:80"
    networks:
      - liveartcorner-network

  web:
    build: .
    command: gunicorn liveartcorner.wsgi:application --bind 0.0.0.0:$PORT --timeout 300 --log-level debug
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw
      - static_volume:/app/staticfiles
    environment:
      - SENTRY_DSN=${LIVEARTCORNER_SENTRY_DSN}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - DOCKERIZED=1
      - PORT=${PORT}
      #- DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} 
      - DATABASE_URL=${DATABASE_URL} # For deployment
    depends_on:
      - db
    restart: always
    networks:
      - liveartcorner-network

networks:
  liveartcorner-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
