# Generated by Django 5.0.6 on 2024-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service", name="duration", field=models.IntegerField(),
        ),
    ]
