# Generated by Django 5.0.6 on 2024-06-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_booking_delete_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
