# Generated by Django 5.0.6 on 2024-06-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_booking_address_booking_name_booking_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="address",),
        migrations.RemoveField(model_name="booking", name="name",),
        migrations.RemoveField(model_name="booking", name="phone",),
    ]
