# Generated by Django 5.0.6 on 2024-08-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_secure_contact_form", "0002_contactformsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomContactMessage",
            fields=[
                (
                    "contactmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_secure_contact_form.contactmessage",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
            ],
            bases=("django_secure_contact_form.contactmessage",),
        ),
    ]
