# Generated by Django 5.0.6 on 2024-08-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartitem_delivery_method_cartitem_discount_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="quantity",
        ),
    ]
