# Generated by Django 5.0.6 on 2024-08-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_cartitem_cart"),
        ("item", "0012_alter_item_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "item")},
        ),
    ]
