# Generated by Django 5.0.6 on 2024-09-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_cartitem_unique_together_cartitem_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="delivery_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.deliverymethod",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="discount_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
