# Generated by Django 5.0.6 on 2024-09-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_alter_cartitem_unique_together_cartitem_added_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="cart.cart"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="delivery_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.deliverymethod",
            ),
        ),
    ]
