# Generated by Django 5.0.6 on 2024-09-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_cartitem_cart_alter_cartitem_delivery_method"),
        ("item", "0012_alter_item_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "item")},
        ),
    ]
