# Generated by Django 4.2.11 on 2024-09-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
