# Generated by Django 4.2.11 on 2024-09-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0012_alter_item_image"),
        ("cart", "0013_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "item")},
        ),
    ]
