# Generated by Django 5.0.6 on 2024-05-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
