# Generated by Django 5.0.6 on 2024-09-13 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_cartitem_cart_alter_cartitem_delivery_method"),
        ("order", "0004_remove_orderitem_delivery_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="discount_code",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="item_total_cost",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cart_item",
            field=models.ForeignKey(
                default=27,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.cartitem",
            ),
            preserve_default=False,
        ),
    ]
