# Generated by Django 4.2.11 on 2024-09-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_orderitem_quantity_alter_orderitem_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity",
        ),
    ]
