# Generated by Django 4.2.11 on 2024-10-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0015_alter_cartitem_unique_together"),
        ("order", "0009_alter_orderitem_cart_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="cart_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.cartitem",
            ),
        ),
    ]
