# Generated by Django 4.2.11 on 2024-10-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0015_alter_cartitem_unique_together"),
        ("order", "0010_alter_orderitem_cart_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="cart_item",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="delivery_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.deliverymethod",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_total_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
